<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'ZfcDatagridExamples\Controller\CategoryController'        => __DIR__ . '/src/ZfcDatagridExamples/Controller/CategoryController.php',
  'ZfcDatagridExamples\Controller\MinimalController'         => __DIR__ . '/src/ZfcDatagridExamples/Controller/MinimalController.php',
  'ZfcDatagridExamples\Controller\PersonController'          => __DIR__ . '/src/ZfcDatagridExamples/Controller/PersonController.php',
  'ZfcDatagridExamples\Controller\PersonDoctrine2Controller' => __DIR__ . '/src/ZfcDatagridExamples/Controller/PersonDoctrine2Controller.php',
  'ZfcDatagridExamples\Controller\PersonZendController'      => __DIR__ . '/src/ZfcDatagridExamples/Controller/PersonZendController.php',
  'ZfcDatagridExamples\Data\Doctrine2'                       => __DIR__ . '/src/ZfcDatagridExamples/Data/Doctrine2.php',
  'ZfcDatagridExamples\Data\PhpArray'                        => __DIR__ . '/src/ZfcDatagridExamples/Data/PhpArray.php',
  'ZfcDatagridExamples\Data\ZendSelect'                      => __DIR__ . '/src/ZfcDatagridExamples/Data/ZendSelect.php',
  'ZfcDatagridExamples\Entity\Person'                        => __DIR__ . '/src/ZfcDatagridExamples/Entity/Person.php',
  'ZfcDatagridExamples\Module'                               => __DIR__ . '/src/ZfcDatagridExamples/Module.php',
  'ZfcDatagridTest\ModuleTest'                               => __DIR__ . '/tests/ZfcDatagridExamplesTest/ModuleTest.php',
);
